### ISSUE TITLE
Default admin credentails not working

### ISSUE THREAD

**Issue by tobievii** [IoT-nxt/prototype#201]
After a fresh install of dev branch , i cannot log in with the admin@localhost.com , admin credentails as per install instructions

**Comment by rvdende** [comment]
It was disabled in 5.1 because I saw abuse and confusion with this setting because user registration was also disabled by default. In the database set level to 100 and admin to true on your user account

Get Outlook for iOS<https://aka.ms/o0ukef>

Kind Regards,

Rouan van der Ende
Software Developer

[cid:iotnxt_923a479a-3b3a-4b43-ab9c-c7272a30fd3f.png]<https://www.iotnxt.com/>


Address: Bylsbridge Office Park, Building 14, Block C, 1st Floor, Alexandra Road, Highveld Ext 73, Centurion, Gauteng, 0046, South Africa
Phone: +27 12 880 0114
Mobile: +27 62 933 1183
Email: rouan.vanderende@iotnxt.com<mailto:rouan.vanderende@iotnxt.com>
Website: https://www.iotnxt.com

[cid:facebook_7fa50cc5-bd2e-456e-b71e-bcc6975537f7.png]<https://www.facebook.com/iotnxt/> [cid:linkedin_de143d75-2ff5-460f-b904-2d40ec2e8b51.png] <https://www.linkedin.com/company/iot.nxt>  [cid:twitter_84ab30d9-fec7-4e63-bb5e-8291caf481e8.png] <https://twitter.com/iot_nxt>  [cid:youtube_7ef73685-9dd4-488f-8407-84b0638dac87.png] <https://www.youtube.com/c/IoTnxt>  [cid:Location-Icon_68f5d1d7-c4ad-447e-8890-cfc8f35cf158.png] <https://bit.ly/2vzWxgi>


[cid:MS_Partner_Signatures---IoT_202249b2-81f8-4812-9dba-8c44e9f947bc.png]

Disclaimer and Confidentiality Notice: IoT.nxt
The information contained in this e-mail communication is confidential. This information is intended solely for the use of the intended recipient named above. If you have received this e-mail communication in error, please notify the sender  rouan.vanderende@iotnxt.com<mailto:rouan.vanderende@iotnxt.com?subject=Disclaimer%20error,%20email%20received%20by%20mistake>  immediately by e-mail if you have received this e-mail by mistake and delete this e-mail from your system. In the event that you are not the intended recipient, you are hereby notified that any disclosure, distribution, use of, printing, copying or other action on the contents of this e-mail communication is strictly prohibited. This e-mail communication and its contents are not intended to be legally binding on IoT.nxt, its affiliates or the sender hereof nor should the contents hereof be construed to amend any contractual arrangement in place, unless explicitly stated herein. IoT.nxt accepts no liability for any loss or damage, whether direct, indirect, consequential or economic, however caused, which may result directly or indirectly from this e-mail communication or from any files attached hereto. Save for bona fide company matters, IoT.nxt does not accept any responsibility for any material, views or opinions contained in this email. This email is further subject to the provisions of the Protection of Personal Information Act 4 of 2013.



________________________________

**Comment by tobievii** [comment]
Tnx, level set, but admin field not found in the collection ?

**Comment by tobievii** [comment]
{ "_id" : ObjectId("5dbb54d84008cf06158f9715"), "uuid" : "xmhkxyp289zo2wf8fltg5ghj9uprjhrbkd57da7qgb94m2cczi258sevr4914oc866sjjt2412k33yyw7qruqxqhaqswn9yeffqeq822ifdjxj7ektk9mj2tsiq4l2ik", "_created_on" : ISODate("2019-10-31T21:40:40.401Z"), "_last_seen" : ISODate("2019-11-01T08:12:07.982Z"), "ip" : "::ffff:85.146.42.92", "userAgent" : "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.70 Safari/537.36", "password" : "53e899ba123d05ec4b19920cd3eab914b9b4daf1ccd8fd7362d826a8d9661870134baa61bd153c59335a5c0e73da265be85965056d405b227deee7cf1391a602", "email" : "tobie.alberts@iotnxt.com", "level" : 100, "apikey" : "v9fxembkl6y33tivdide8hrc5d4nysnz", "publickey" : "9mfjgcx87q1e7llaj0bg7vgs1jp5lqzd", "username" : "tobiealberts8639", "ipLoc" : { "range" : [ 1435641856, 1435642879 ], "country" : "NL", "region" : "ZH", "eu" : "1", "timezone" : "Europe/Amsterdam", "city" : "The Hague", "ll" : [ 52.0544, 4.2477 ], "metro" : 0, "area" : 1 } }

**Comment by rvdende** [comment]
yes, the admin field is not created automatically, but is checked for.
Just add it on your account `"admin" : true` and refresh

**Comment by tobievii** [comment]
Works thank you !
